### ISSUE TITLE
Reproducing the same training dataset

### ISSUE THREAD

**Issue by zerocstaker** [JohnGiorgi/DeCLUTR#162]
Hi,
Thank you for the great paper and code!

I want to reproduce the results and I am not sure about the exact steps to reproduce the training dataset from OpenWebText. I downloaded the entire OpenWebText from the corpus and removed documents that have a length of less than 2048 after Roberta tokenization. This leaves me with 812,436 documents.

In your paper, you reported that you got 495,243 documents from a subset, and I am wondering how I can reproduce that? I see that there is a max_documents argument for the preprocessing script. If you used that, can you tell me the arguments you used for the script?

**Comment by JohnGiorgi** [comment]
Hey @zerocstaker,

Thanks for reaching out. Firstly, I am going to download a fresh copy of OpenWebText and run my script to see if everything checks out. This will take some time. In the meantime, here is the code I ran when I first generated the training data months ago:

```bash
python scripts/preprocess_openwebtext.py "/Users/johngiorgi/Downloads/openwebtext" "/Users/johngiorgi/Downloads/openwebtext-2048/train.txt" --min-length 2048
```

**Comment by zerocstaker** [comment]
Thanks for the quick response! I am using pretrained roberta-base tokenizer without special tokens to determine the length. It does take a long time to process everything (around 6 hours).

Nevertheless, I got almost double the number of documents than what you reported, and so I want to make sure if I did anything correctly. One thing I suspect that may be happening is that tokenizer splits some words into multiple tokens and thus allow more documents, which have less than 2048 tokens if split by spaces, to be considered valid. I will try to do it with whitespace, which won't take too much time, and report back the number of documents.

**Comment by JohnGiorgi** [comment]
@zerocstaker No problem. Yes, it is expected that you are getting more documents with over 2048 wordpiece tokens. Let me know if the results with whitespace tokenization are expected (I think they will be).

**Comment by zerocstaker** [comment]
Hi John, with splitting by space, I am now able to get 497,864, which is similar to what is reported in the paper. The difference in the number of documents may come from how I unzip the things (I remembered I didn't get any error with tar), but I think it is close enough and should result in similar results. Thanks!
