### ISSUE TITLE
Can't load weights for 'johngiorgi/declutr-sci-base'

### ISSUE THREAD

**Issue by GabrielLin** [JohnGiorgi/DeCLUTR#169]
When I would like to load the model from Transformer, I am facing the following issue. Could you help? Thanks.
```
OSError: Can't load weights for 'johngiorgi/declutr-sci-base'. Make sure that:

- 'johngiorgi/declutr-sci-base' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'johngiorgi/declutr-sci-base' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.


```

**Comment by JohnGiorgi** [comment]
Can you please copy and paste the exact code you are using to load the model?

**Comment by GabrielLin** [comment]
@JohnGiorgi Thanks for your reply. I am sorry. I think it is my network issue. I put my code to another server with different IP and it is OK.

**Comment by JohnGiorgi** [comment]
No worries, feel free to open issues if you have other troubles.
