### ISSUE TITLE
What is the max length of the text for the DeCLUTR-small model input?

### ISSUE THREAD

**Issue by lessenko** [JohnGiorgi/DeCLUTR#185]
What is the max length of the text for the DeCLUTR-small model input?

Thanks.

**Comment by JohnGiorgi** [comment]
512, the same as the underlying pretrained models.

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("johngiorgi/declutr-small")
print(tokenizer.model_max_length)  # 512

tokenizer = AutoTokenizer.from_pretrained("distilroberta-base")
print(tokenizer.model_max_length)  # 512
```

DeCLUTR-base is also 512.

**Comment by lessenko** [comment]
Thanks.
Just in case  I tried Universal Sentence Encoder (https://tfhub.dev/google/universal-sentence-encoder/4).
It permits to use more large text input, but it is for TensorFlow.

**Comment by JohnGiorgi** [comment]
No problem. Just note that our models are more comparable to https://tfhub.dev/google/universal-sentence-encoder-large/5 than https://tfhub.dev/google/universal-sentence-encoder/4.

Also, if your text is longer than 512 tokens, you can try breaking it into chunks of 512, embedding each chunk independently, and then averaging the chunk embeddings to get a single embedding.

**Comment by lessenko** [comment]
Thanks. I might try it.

**Comment by JohnGiorgi** [comment]
Cool, feel free to open a new issue or re-open this one if you have DeCLUTR specific questions!
