### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by TYXguo** [JohnGiorgi/DeCLUTR#198]
When I try to run the code, I get the error like "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)".

With the warning like "- INFO - allennlp.common.plugins - Plugin declutr available"
                                   " - WARNING - allennlp.common.params - error loading _jsonnet (this is expected on Windows), treating training_config\declutr.jsonnet as plain json"

How can I solve this problem？

Thank you!

**Comment by JohnGiorgi** [comment]
Are you on Windows? Guessing based on the error message "`(this is expected on Windows)`". Unfortunately AllenNLP (which DeCLUTR is implemented in) does not currently support Windows, see [here](https://github.com/allenai/allennlp/blob/5974f54e9388fa2e8ea363c3865e505b2bab0c45/README.md#installation).

Do you need to train the model, or can you use one of the pretrained models? They are available [here](https://huggingface.co/johngiorgi) and don't require the installation of this repo (or AllenNLP).

**Comment by TYXguo** [comment]
I'm very sorry I ignored this important information, I will try again on linux, thank you for your help！

**Comment by JohnGiorgi** [comment]
Closing, but please feel free to re-open or open a new issue if you have questions.
