### ISSUE TITLE
How to save model as a transformer model?

### ISSUE THREAD

**Issue by tagizaade** [JohnGiorgi/DeCLUTR#205]
Hi there,

I trained using colab sample on my corpus successfully, but I couldn't find a way to dump the model as a transformer model .
How I can do that?

Thanks.

**Comment by JohnGiorgi** [comment]
Hi,

> I trained using colab sample on my corpus successfully, but I couldn't find a way to dump the model as a transformer model. How I can do that?

Awesome! We have a script for just that purpose actually, [here](https://github.com/JohnGiorgi/DeCLUTR/blob/master/scripts/save_pretrained_hf.py). Will you try that and let me know if it works?

I will also update the readme and notebook to point out this script.

**Comment by tagizaade** [comment]
> 
> Awesome! We have a script for just that purpose actually, [here](https://github.com/JohnGiorgi/DeCLUTR/blob/master/scripts/save_pretrained_hf.py). Will you try that and let me know if it works?
> 

Thank you John. It worked.

**Comment by kingafy** [comment]
Do we need to pass the output directory as argument to saving the model as hf?

**Comment by kingafy** [comment]
I have trained the model but what are the arguments to pass and what file from Declutr training to get the corresponding hf model in the script save_pretrained_hf???

**Comment by kingafy** [comment]
Instructions passed to save:-
ARCHIVE_FILE = "/content/output/training_state_epoch_0.th" 
SAVE_DIRECTORY = "/content/final_model/"

!python save_pretrained_hf.py ARCHIVE_FILE $ARCHIVE_FILE --SAVE_DIRECTORY $SAVE_DIRECTORY

**Comment by JohnGiorgi** [comment]
@kingafy Just pass to `save_pretrained_hf.py` the same directory path you provided to the `--serialization-dir` argument of the `allennlp train` command. E.g. if you passed `--serialization-dir "output"`, you would call

```bash
python save_pretrained_hf.py --archive-file "output" --save-directory "output_transformers"
```

`"output_transformers"` would now contain a model you could load with Hugging Face Transformers, e.g.

```python
from transformers import AutoTokenizer, AutoModelForMaskedLM
  
tokenizer = AutoTokenizer.from_pretrained("output_transformers")
model = AutoModel.from_pretrained("output_transformers")
```

Please see #206 for more documentation.
