### ISSUE TITLE
Can we do transfer learning of ur model trained on wikipedia on our custom dataset. 

### ISSUE THREAD

**Issue by kingafy** [JohnGiorgi/DeCLUTR#217]
I have close to 500 documents on a particular domain. I want to use previous wikipedia based trained model checkpoint(https://huggingface.co/johngiorgi/declutr-base)   to train on my custom data. Is there a way to do it. From the notebook it seems we need to train the declutr model from scratch.Any advice or suggestions how we can use the last checkpoint to finetune on our dataset.

**Comment by JohnGiorgi** [comment]
Yes, this should be possible. I might be able to write a notebook or update one of the existing ones with instructions, but it will probably take me about a week. 

In case you want to get started before then, the general steps would be to:

1. Download the pretrained AllenNLP model [here](https://github.com/JohnGiorgi/DeCLUTR/releases/download/v0.1.0rc1/declutr-base.tar.gz). Unzip this, and keep track of its `best.th` file.
2. Add the following to your config, under the `"model"` key:

```json
"model":
    // ...other stuff here
    "initializer": {
        "regexes": [
            [".*", {"type": "pretrained", "weights_file_path": "path/to/declutr-base/best.th"}],
        ]
    }
}
```

This is not unique to DeCLUTR or our repo, it is just how you use transfer learning in AllenNLP. So its probably worth it to checkout the relevant AllenNLP documentation (e.g. [here](https://docs.allennlp.org/main/api/nn/initializers/#PretrainedModelInitializer)) and maybe even [their guide](https://guide.allennlp.org/) if you are not familiar with AllenNLP.

FYI, https://huggingface.co/johngiorgi/declutr-base was not trained on Wikipedia solely, but on [OpenWebText](https://skylion007.github.io/OpenWebTextCorpus/), which contains stuff other than Wikipedia.

**Comment by kingafy** [comment]
Thanks a lot for your help.It worked.

**Comment by JohnGiorgi** [comment]
Awesome :)
