### ISSUE TITLE
Cant set up DECLUTR in local AWS linux machine

### ISSUE THREAD

**Issue by kingafy** [JohnGiorgi/DeCLUTR#223]
I am getting the following error while trying to install:-
Running setup.py install for jsonnet ... error
    ERROR: Command errored out with exit status 1:
     command: /home/dir/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-17ky483c/jsonnet_5b04eae0f0b449259315a39679254ec4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-17ky483c/jsonnet_5b04eae0f0b449259315a39679254ec4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-czlcglsf/install-record.txt --single-version-externally-managed --compile --install-headers //home/dir/bin/python3/include/site/python3.6/jsonnet
         cwd: /tmp/pip-install-17ky483c/jsonnet_5b04eae0f0b449259315a39679254ec4/
    Complete output (23 lines):
    running install
    running build
    running build_ext
    g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json core/desugarer.cpp -o core/desugarer.o
    g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json core/formatter.cpp -o core/formatter.o
    g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json core/libjsonnet.cpp -o core/libjsonnet.o
    g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json core/lexer.cpp -o core/lexer.o
    g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json core/parser.cpp -o core/parser.o
    g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json core/pass.cpp -o core/pass.o
    g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json core/static_analysis.cpp -o core/static_analysis.o
    g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json core/string_utils.cpp -o core/string_utils.o
    g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json core/vm.cpp -o core/vm.o
    g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json third_party/md5/md5.cpp -o third_party/md5/md5.o
    building '_jsonnet' extension

**Comment by JohnGiorgi** [comment]
Hi,

This doesn't look to be a DeCLUTR specific problem. From the looks of it, [`jsonnet`](https://pypi.org/project/jsonnet/), which is a dependency of AllenNLP, is not installing correctly. I would try to diagnose the reason why `jsonnet` is not installing, and once that is fixed, install DeCLUTR.

**Comment by JohnGiorgi** [comment]
Closing, feel free to re-open if the issue wasn't addressed.
