### ISSUE TITLE
argument 'lazy' for dataset_reader

### ISSUE THREAD

**Issue by negar-mokhberian** [JohnGiorgi/DeCLUTR#226]
Hi,
I am using allennlp version 2.5.0 and I get the error:
`TypeError: __init__() got an unexpected keyword argument 'lazy'`
I am not sure how to resolve this problem.
I would appreciate any help on this issue.

**Comment by JohnGiorgi** [comment]
Hi, AllenNLP > 2.0 causes all sorts of issues. Will you install one of the AllenNLP versions specificed in the `setup.py`

https://github.com/JohnGiorgi/DeCLUTR/blob/96c6f895ba048f392663921fb866e3966cc27b48/setup.py#L44

This is what will be installed if you follow the [installation instructions in the readme](https://github.com/JohnGiorgi/DeCLUTR#installation).

**Comment by negar-mokhberian** [comment]
Thanks, it works now!
