### ISSUE TITLE
Minimum text length violated despite preprocessing

### ISSUE THREAD

**Issue by julianbernado** [JohnGiorgi/DeCLUTR#233]
What is the tokenizer used to calculate the minimum lengths during the preprocessing involved in training? As I understand from looking at the code, it should be either the Tokenizer for the given pretrained model or the SpacyTokenizer. Yet, I have pared down my dataset to only include texts whose length exceeds my needed minimum length according to both of these tokenizers, but still run into the following error:

`ValueError: len(tokenizer(text)) should be at least 24 (num_anchors * max_span_len * 2), got 23`

I don't believe there to be any issues in the code used when I slim my dataset down, but I am possibly missing a different tokenizer that is used when preprocessing the dataset.

**Comment by JohnGiorgi** [comment]
This check uses the `tokenizer` passed to `dataset_reader.py` IF it is a `PretrainedTransformerTokenizer`. Otherwise is uses `.split()`.

Did you use the same tokenizer to filter your dataset as the tokenizer you passed to `dataset_reader.py`?

**Comment by repodiac** [comment]
Hi, I have a similar issue: I get `ValueError: len(tokenizer(text)) should be at least <number here> (num_anchors * max_span_len * 2), got 0`

I have filtered my input data to have both minimum length beyond parameter `min_length` and greater than 0, of course! I also tried to print out the text to be tokenized, it was empty!? How can that be?

I use a pretrained model from Sentence Transformers, `sentence-transformers/paraphrase-multilingual-mpnet-base-v2`, so the tokenizer comes from that model - do you have any idea, why the **text is empty**?
