### ISSUE TITLE
Strange issue occuring during Training

### ISSUE THREAD

**Issue by kingafy** [JohnGiorgi/DeCLUTR#238]
Team,
I have been using Declutr for last few months and have trained various models. A strange issue is surfacing. currently, When I convert the model to hugging face from using the code save_pretrained.py code there are 7 files getting created where as earlier it were 6 files. The extra file is of tokenizer.json file. When I consume this model , I am not able to load in Autotokenizer which gives me strange issues. Any idea why additional files are getting generated .IS it due to any environmental glitch or training data issue?

**Comment by JohnGiorgi** [comment]
Closing this, please feel free to re-open if you are still having trouble.
