### ISSUE TITLE
Installation fails in colab notebook

### ISSUE THREAD

**Issue by moruga123** [JohnGiorgi/DeCLUTR#264]
The installation command (!pip install git+https://github.com/JohnGiorgi/DeCLUTR.git) in the colab notebook fails with:

    ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
    torchvision 0.14.1+cu116 requires torch==1.13.1, but you have torch 1.6.0 which is incompatible.
    torchtext 0.14.1 requires torch==1.13.1, but you have torch 1.6.0 which is incompatible.
    torchaudio 0.13.1+cu116 requires torch==1.13.1, but you have torch 1.6.0 which is incompatible.
    fastai 2.7.11 requires torch<1.14,>=1.7, but you have torch 1.6.0 which is incompatible.
    en-core-web-sm 3.4.1 requires spacy<3.5.0,>=3.4.0, but you have spacy 2.3.9 which is incompatible.
    confection 0.0.4 requires srsly<3.0.0,>=2.4.0, but you have srsly 1.0.6 which is incompatible.
    Successfully installed allennlp-1.1.0 boto3-1.26.83 botocore-1.29.83 catalogue-1.0.2 declutr-0.1.0rc1 filelock-3.0.12 jmespath-1.0.1 jsonnet-0.19.1 jsonpickle-3.0.1 overrides-3.1.0 plac-1.1.3 pytorch-metric-learning-2.0.1 s3transfer-0.6.0 sacremoses-0.0.53 sentencepiece-0.1.97 spacy-2.3.9 srsly-1.0.6 tensorboardX-2.6 thinc-7.4.6 tokenizers-0.8.1rc1 torch-1.6.0 transformers-3.0.2 validators-0.20.0

Confirming that this is a failure, the next notebook cell doesn't work:

    Traceback (most recent call last):
      File "preprocess_wikitext_103.py", line 10, in <module>
        from declutr.common.util import sanitize_text
    ModuleNotFoundError: No module named 'declutr'

What adjustments are needed are needed to make it work?
I haven't been able to get it to install correctly in a plain linux environment either, but I think addressing the colab notebook is a better starting point since that notebook+environment combination might 'always' be expected to be working.

**Comment by JohnGiorgi** [comment]
Hmm, I wasn't able to reproduce this. I can open the `training.ipynb` notebook in colab and `Runtime > Run all` without issue.

More generally, that snippet you posted is not an error traceback saying `declutr` wasn't installed; it is just `pip`'s dependency resolver reporting some conflicts. I might need more information to help, e.g. which notebook is it that is not working.

**Comment by moruga123** [comment]
The error seems to have gone away by itself. I wonder if there was a temporary problem in some remote pip repository that was fixed.

I was not able to successfully `pip install git+https://github.com/JohnGiorgi/DeCLUTR.git` in linux in python 3.9.6, but it worked without errors in 3.8.10 (same version as colab notebook).
